import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// --- 修改后的导入语句 ---
// 修正了相对路径 (./styles/ 而不是 ./pre-triage/styles/)
// 修正了文件名 (pre-globals.css 而不是 globals.css)
// 如果开发者意图是导入 styles.css，则应改为 import './styles/styles.css';
import './styles/pre-globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App", // 您可能也想修改这里的标题
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-CN" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-background text-foreground">
        {children}
      </body>
    </html>
  );
}

